LIST = {'Vector': '维克托',
        '特工Vector': '特工维克托',
        'Spectre M4': '幽灵M4',
        'Super SASS': 'S-SASS',
        'Bren Ten': '布伦·坦',
        'USP Compact': 'USP-C',
        'Five-seveN': 'FN-57',
        'Super-Shorty': '超级肖蒂',
        'Saiga-12': '塞伽12型',
        'Spitfire': '喷火',
        'Six12': 'CPS-12',
        'INSAS': '英萨斯',
        'AK-Alfa': 'AK-阿尔法',
        'Rex Zero 1': 'Rex-0-1',
        'Lusa': '卢萨',
        'AUG Para': 'AUG SMG',
        'Savage 99': '沙维奇99型'}
